### ISSUE TITLE
sc_clustering does not converge to the optimal solution

### ISSUE THREAD

**Issue by jcredberry** [fsavje/Rscclust#11]
Dear Fredrik,

I have tried this package with a simple problem of 50 data points. I have solved it with a genetic algorithm for two clusters, of which one has 26 points and the other 24. The global minimum has a sum of distances of about 168.6613. A local minimum has a sum of distances of about 185.4753. 

Using `sc_clustering`, I need to fix the size constraint to 20 (`my_clustering <- `sc_clustering`(my_dist, 20)`). The solution I get points to the local minimum, not the global one. Is there something in the configuration of `sc_clustering` that I have not correctly set up?

If you need it, I am attaching the dataset for your evaluation.

Regards,
Julio

[Matriz50.csv](https://github.com/fsavje/scclust-R/files/8200233/Matriz50.csv)

**Comment by fsavje** [comment]
Dear Julio,

Thanks for the report. `scclust` implements an approximation algorithm, meaning that it does not guarantee to produce a global minimum. The size constrained clustering problem is NP-hard, meaning that it is not possible to find the global minimum unless the number of data points is very small (such as in your example). `scclust` is made for setting with millions or billions of data points, and it would take an unreasonable long time to find the global minimum in that case (as in billions of years). What `scclust` does is to provide a solution that is guaranteed to be within a certain factor of the global minimum, meaning that it's approximately optimal. That is what you discovered in your example. There is no way that `scclust` can be configured to ensure that it produces global minimums.

On a side note, it seems you picked the size constraint to be 20 to force the algorithm to produce two clusters. This is not advisable. The point with `scclust` is to enforce a size constraint in cases we are (somewhat) indifferent to how many clusters are produced. If you want a clustering that has a specific number of clusters, you should probably not use `scclust`. (This is especially true when the data set is large and you want a relatively small number of clusters, because the algorithm scales poorly in the size constraint.)

**Comment by jcredberry** [comment]
Thanks for clearing my doubts up, Fredrik. I was looking for a size constrained algorithm that worked with hundreds of data points (NP-hard, as you stated) and produced two clusters, one with `floor(n/2)+1` elements (hence the need for setting the size constraint to be 20). I think running a genetic algorithm will be the way to go for the moment, as I developed an algorithm, and it also has problems finding a global optimum, although it gets pretty close most of the time.

Good luck with this package.

Regards, 
Julio

**Comment by fsavje** [comment]
Using a genetic algorithm seems reasonable in your setting. If you want, you could use the output from `scclust` as one candidate solution in your candidate solution pool. There no guarantee that it will be close to the global optimum, but it could be close, and it will not hurt.

Good luck with your project!
