### ISSUE TITLE
Setting number of clusters?

### ISSUE THREAD

**Issue by MatthieuStigler** [fsavje/Rscclust#8]
Hi Fredrik!

Is there a way to set the exact number of clusters desired, on top of the cluster minimum size? Maybe in a second agglomerative step?

The problem is I am only interested in a few clusters, typically 3-10. I tried in the example to set `size_constraint=50000/10` but it seems `sc_clustering` is very slow at creating clusters with large minimum size? Try:

    example(sc_clustering)
    my_clustering <- sc_clustering(my_dist, size_constraint=50000/10)

Thanks!

**Comment by fsavje** [comment]
Hi Matthieu!

Thanks for reaching out. 

It is not possible to specify an exact number of clusters in scclust. You could do it recursively by, for example, running the algorithm on the centroids of clusters until you have the desired number of clusters. But a better way would probably be to use an algorithm that explicitly allow you to set a number of desired clusters. This is the default for clustering algorithms, and scclust was built to complement those other approaches. See, for example, https://en.wikipedia.org/wiki/K-means_clustering (and the `kmeans()` function in R).

scclust does not scale well with the size constraint. That constraint should be used for actual constraints rather than controlling the number of clusters.

**Comment by MatthieuStigler** [comment]
Hi Fredrik!

Thanks for the answer. Well my goal was to have an algorithm that allows me both to set the number of desired clusters but also to set a minimum number of observations in each cluster. So unfortunately it seems that won't be possible with `scclust` nor with any of the standard clustering algorithms in R à la `kmeans` :-(

Thanks anyway!

**Comment by fsavje** [comment]
I see. In that case, my recommendation would be to do it in two clustering steps:

1. First, run scclust with the minimum size requirements. You will likely get way too many clusters than what you want.
2. Make a reduced data set where each data point is the centroid of a cluster from step 1.
3. Run a standard clustering algorithm, e.g., kmeans, on the reduced data set. You now have the desired number of clusters.
4. Assign the cluster labels from step 3 to all units in the corresponding clusters from step 1.

The optimality guarantees from scclust won't hold here, but it should perform reasonably well in general.

Hope this helps.

**Comment by MatthieuStigler** [comment]
great, thanks for the hint!
